# Generated by Django 2.1.3 on 2018-11-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20181105_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prirss',
            name='url',
            field=models.CharField(blank=True, max_length=5124, verbose_name='URL'),
        ),
    ]
