# Generated by Django 2.1.3 on 2018-11-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetRSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('link', models.CharField(max_length=5124, verbose_name='URL')),
                ('time', models.DateTimeField(blank=True, default=0, verbose_name='時間')),
                ('category', models.IntegerField(blank=True, default=0, verbose_name='カテゴリ')),
                ('flag', models.IntegerField(blank=True, default=0, verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='priRSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=5124, verbose_name='URL')),
            ],
        ),
        migrations.RemoveField(
            model_name='impression',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Impression',
        ),
    ]
